FROM node:18.8.0-alpine AS buildBlog

WORKDIR /app/blog

COPY blog/package*.json ./

RUN npm install

COPY ./blog ./

RUN npm run build


FROM node:18.8.0-alpine AS buildDictionary

WORKDIR /app/dictionary

COPY dictionary/package*.json ./

RUN npm install

COPY ./dictionary ./

RUN npm run build

FROM nginx:1.13

COPY --from=buildBlog /app/blog/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=buildDictionary /app/dictionary/nginx.conf /etc/nginx/conf.d/dictionary.vanbaviet.com.conf
COPY ./llama3/nginx.conf /etc/nginx/conf.d/llama3.vanbaviet.com.conf

COPY --from=buildBlog /app/blog/dist /usr/share/nginx/html/blog
COPY --from=buildDictionary /app/dictionary/dist /usr/share/nginx/html/dictionary

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]