version: '3.3'

services:
  frontend:
    build: ./Frontend
    image: frontend
    restart: always
    ports:
      - 80:80
  api-gateway:
    build: ./Backend/api-gateway
    image: api-gateway
    restart: always
    env_file:
      - ./Backend/.env
    volumes:
      - ./logs:/var/log
  auth-service:
    build: ./Backend/authservice
    image: auth-service
    restart: always
    env_file:
      - ./Backend/.env
    volumes:
      - ./logs:/var/log
  question-service:
    build: ./Backend/question
    image: question-service
    restart: always
    env_file:
      - ./Backend/.env
    volumes:
      - ./logs:/var/log
  mail-service:
    build: ./Backend/mailservice
    image: mail-service
    restart: always
    env_file:
      - ./Backend/.env
    volumes:
      - ./logs:/var/log
  location-service:
    build: ./Backend/vnlocation-api
    image: location-service
    restart: always
    env_file:
      - ./Backend/.env
    volumes:
      - ./logs:/var/log
  article-service:
    build: ./Backend/article
    image: article-service
    restart: always
    env_file:
      - ./Backend/.env
    volumes:
      - ./logs:/var/log
  dictionary-service:
    build: ./Backend/dictionary
    image: dictionary-service
    restart: always
    env_file:
      - ./Backend/.env
    volumes:
      - ./logs:/var/log
  server-registry:
    build: ./Backend/server-registry
    image: server-registry
    restart: always
    env_file:
      - ./Backend/.env
    volumes:
      - ./logs:/var/log
    ports:
      - 8761:8761
  googledrive-store:
    build: ./Backend/googledrive-store
    image: googledrive-store
    restart: always
    env_file:
      - ./Backend/.env
    volumes:
      - ./logs:/var/log
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./Backend/sql.env
    volumes:
      - ./Backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7.2.4-alpine
    restart: always
    build: ./Backend/redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data:
