server:
  port: '8082'
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
spring:
  application:
    name: "auth-service"
  datasource:
    username: ${JDBC_DATABASE_USERNAME}
    url: ${JDBC_DATABASE_URL}${AUTH_SERVICE_DATABASE_NAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
log_path:
  folder: /var/log/auth-service/
  file: /auth-service
eureka:
  instance:
    hostname: ${SERVER_REGISTRY_NAME:localhost}
    port: ${SERVER_REGISTRY_PORT:8761}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/