server:
  port: '8088'
spring:
  application:
    name: "dictionary-service"
  datasource:
    username: ${JDBC_DATABASE_USERNAME}
    url: ${JDBC_DATABASE_URL}${DICTIONARY_SERVICE_DATABASE_NAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
log_path:
  folder: /var/log/dictionary-service/
  file: /dictionary-service
eureka:
  instance:
    hostname: ${SERVER_REGISTRY_NAME:localhost}
    port: ${SERVER_REGISTRY_PORT:8761}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
wordsapi:
  key: ${WORDSAPI_KEY}
  host: ${WORDSAPI_HOST:wordsapiv1.p.rapidapi.com}