server:
  port: 8086
spring:
  application:
    name: gooogledrive-store
  datasource:
    username: ${JDBC_DATABASE_USERNAME}
    url: ${JDBC_DATABASE_URL}${GOOGLE_DRIVE_DATABASE_NAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
google:
  drive:
    root-dictionary: ${ROOTDICTIONARY_GOOGLEDRIVE}
eureka:
  instance:
    hostname: ${SERVER_REGISTRY_NAME:localhost}
    port: ${SERVER_REGISTRY_PORT:8761}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/