server:
  port: '8083'
spring:
  datasource:
    username: ${JDBC_DATABASE_USERNAME}
    url: ${JDBC_DATABASE_URL}${LOCATION_SERVICE_DATABASE_NAME}
    password: ${JDBC_DATABASE_PASSWORD}
  application:
    name: "VietNamLocationApi-service"
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: none
log_path:
  folder: "/var/log/location-service/"
  file: "/location-service"
eureka:
  instance:
    hostname: ${SERVER_REGISTRY_NAME:localhost}
    port: ${SERVER_REGISTRY_PORT:8761}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/