jwt:
  secret: ${JWT_SECRET}
server:
  port: '8080'
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: ${ALLOWED_ORIGINS:}
            allowedMethods:
              - GET
              - HEAD
              - POST
              - PUT
              - DELETE
              - TRACE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "Authorization"
              - "Content-Type"
            allowCredentials: ${ALLOW_CREDENTIALS:}
            maxAge: 3600
log_path:
  folder: "/var/log/api-gateway/"
  file: "/api-gateway"
name:
  services:
    auth: ${AUTH_SERVICE_NAME:auth-service}
    mail: ${MAIL_SERVICE_NAME:mail-service}
    question: ${QUESTION_SERVICE_NAME:question-service}
    location: ${LOCATION_SERVICE_NAME:location-service}
    google: ${GOOGLE_SERVICE_NAME:googledrive-store}
eureka:
  instance:
    hostname: ${SERVER_REGISTRY_NAME:localhost}
    port: ${SERVER_REGISTRY_PORT:8761}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/