server:
  port: '8084'
spring:
  application:
    name: "question-service"
  datasource:
    url: ${JDBC_DATABASE_URL}${QUESTION_SERVICE_DATABASE_NAME}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
log_path:
  folder: "/var/log/question-service/"
  file: "/question-service"
eureka:
  instance:
    hostname: ${SERVER_REGISTRY_NAME:localhost}
    port: ${SERVER_REGISTRY_PORT:8761}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/